name: 'Tests'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3

      - name: Gentleman
        run: echo 'Hello, World!'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: jest src
